export const mockData = [
  {
    id: '1',
    title: 'Buy Roomba',
    description: 'Find and purchase a Roomba vacuum cleaner.',
    context: 'home',
  },
  {
    id: '2',
    title: 'Fix car brakes',
    description: 'Schedule an appointment with the mechanic to fix the brakes.',
    context: 'car',
  },
  {
    id: '3',
    title: 'Refactor codebase',
    description: 'Improve the structure of the existing codebase.',
    context: 'coding',
  },
  {
    id: '4',
    title: 'Respond to client emails',
    description: 'Reply to all pending client emails from this week.',
    context: 'email',
  },
  {
    id: '5',
    title: 'Clean the garage',
    description: 'Organize and clean the garage.',
    context: 'home',
  },
  {
    id: '6',
    title: 'Submit tax documents',
    description: 'Complete and submit all necessary tax documents.',
    context: 'admin',
  },
  {
    id: '7',
    title: 'Call John about project update',
    description: 'Discuss the current status of the project with John.',
    context: 'phone',
  },
  {
    id: '8',
    title: 'Research TypeScript best practices',
    description: 'Look up the latest best practices for TypeScript development.',
    context: 'research',
  },
  {
    id: '9',
    title: 'Buy groceries',
    description: 'Purchase weekly groceries from the supermarket.',
    context: 'shopping',
  },
  {
    id: '10',
    title: 'Change car oil',
    description: "Get the car's oil changed at the service station.",
    context: 'car',
  },
  {
    id: '11',
    title: 'Implement new feature',
    description: 'Add the new feature to the project as discussed.',
    context: 'coding',
  },
  {
    id: '12',
    title: 'Draft meeting minutes',
    description: 'Write and distribute the minutes of the last meeting.',
    context: 'email',
  },
  {
    id: '13',
    title: 'Organize kitchen pantry',
    description: 'Sort and organize items in the kitchen pantry.',
    context: 'home',
  },
  {
    id: '14',
    title: 'Prepare budget report',
    description: 'Compile and prepare the monthly budget report.',
    context: 'admin',
  },
  {
    id: '15',
    title: 'Follow up with client on call',
    description: 'Call the client to follow up on the latest proposal.',
    context: 'phone',
  },
  {
    id: '16',
    title: 'Study JavaScript frameworks',
    description: 'Research and compare popular JavaScript frameworks.',
    context: 'research',
  },
  {
    id: '17',
    title: 'Order new office supplies',
    description: 'Purchase necessary office supplies for the team.',
    context: 'shopping',
  },
  {
    id: '18',
    title: 'Wash the car',
    description: 'Clean the exterior and interior of the car.',
    context: 'car',
  },
  {
    id: '19',
    title: 'Fix website bugs',
    description: 'Identify and fix bugs reported on the website.',
    context: 'coding',
  },
  {
    id: '20',
    title: 'Send thank you emails',
    description: 'Email thank you notes to all participants of the event.',
    context: 'email',
  },
];
